version: 3

services:
  server:
    image: ./server
    hostname: server
    container_name: gsabot-server
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  client:
    image: ./client
    hostname: client
    container_name: gsabot-client
    restart: unless-stopped
    environment:
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gsabot
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: gsabot
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped