version: 3

services:
  server:
    build: 
      context: ./server
      args:
        DB_HOST: gsabot-db
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
    container_name: gsabot-server
    restart: unless-stopped
    ports:
      - "8080:80"
    depends_on:
      - db
  client:
    build: 
      context: ./client
      args:
        DB_HOST: gsabot-db
        DB_PORT: ${DB_PORT}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_NAME: ${DB_NAME}
        CLIENT_ID: ${CLIENT_ID}
        GUILD_ID: ${GUILD_ID}
        DISCORD_TOKEN: ${DISCORD_TOKEN}
        DOMAIN: ${DOMAIN}
        MINECRAFT_SUBDOMAIN: ${MINECRAFT_SUBDOMAIN}
        SERVER_SUBDOMAIN: ${SERVER_SUBDOMAIN}
        SCHOOL: ${SCHOOL}
        SCHOOL_CODE: ${SCHOOL_CODE}
        REGISTER: ${REGISTER}
        GSA_BANNER: ${GSA_BANNER}
    container_name: gsabot-client
    restart: unless-stopped
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: gsabot
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: gsabot
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped